const Services = [
    {
        Id: '1',
        sImgS: 'images/service-single/graphics/imresizer-1735401291668.jpg',
        sTitle: 'Graphic Design',
        description: 'Creating visually compelling designs that effectively convey your brand message.',
        des2: 'Specializing in logo design, promotional materials, and branding assets to captivate your audience.',
        des3: 'Delivering impactful visuals that align with your business goals and values.',
        icon: 'flaticon-vector',
        ssImg1: 'images/service-single/graphics/images (1).jpg',
        ssImg2: 'images/service-single/graphics/img-3.jpg',
    },
    {
        Id: '2',
        sImgS: 'images/service-single/brand/img-1.jpg',
        sTitle: 'Figma Design',
        description: 'Crafting modern and intuitive designs using Figma to enhance user experiences.',
        des2: 'Expert in prototyping and creating collaborative design workflows with Figma.',
        des3: 'Delivering scalable and responsive designs tailored to meet your project needs.',
        icon: 'flaticon-palette',
        ssImg1: 'images/service-single/brand/img-2.jpg',
        ssImg2: 'images/service-single/brand/img-3.jpg',
    },
    {
        Id: '3',
        sImgS: 'images/service-single/ux/img-1.jpg',
        sTitle: 'UI/UX Design',
        description: 'Designing seamless user interfaces and experiences to engage your audience.',
        des2: 'Creating user-friendly designs that balance aesthetics and functionality.',
        des3: 'Expert in wireframes, prototypes, and interactive designs for web and mobile apps.',
        icon: 'flaticon-add',
        ssImg1: 'images/service-single/ux/img-2.jpg',
        ssImg2: 'images/service-single/ux/img-3.jpg',
    },
    {
        Id: '4',
        sImgS: 'images/service-single/development/img-1.jpg',
        sTitle: 'Web Development',
        description: 'Building modern, secure, and scalable websites using cutting-edge technologies.',
        des2: 'Expert in the MERN stack for high-performance and interactive web solutions.',
        des3: 'Delivering customized, responsive websites to elevate your online presence.',
        icon: 'flaticon-coding',
        ssImg1: 'images/service-single/development/img-2.jpg',
        ssImg2: 'images/service-single/development/img-3.jpg',
    },
    {
        Id: '5',
        sImgS: 'images/service-single/app/img-1.jpg',
        sTitle: 'App Development',
        description: 'Creating innovative mobile applications that deliver exceptional user experiences.',
        des2: 'Expert in building cross-platform apps for Android and iOS with a focus on performance.',
        des3: 'Customizing app solutions tailored to meet unique business and user needs.',
        icon: 'flaticon-app-development',
        ssImg1: 'images/service-single/app/img-2.jpg',
        ssImg2: 'images/service-single/app/img-3.jpg',
    },
    {
        Id: '6',
        sImgS: 'images/service-single/softwere/img-1.jpg',
        sTitle: 'Software Development',
        description: 'Developing high-quality, scalable software solutions tailored to your business goals.',
        des2: 'Expert in delivering custom solutions to enhance productivity and efficiency.',
        des3: 'Using modern technologies to ensure performance, reliability, and security.',
        icon: 'flaticon-smartphone',
        ssImg1: 'images/service-single/softwere/img-2.jpg',
        ssImg2: 'images/service-single/softwere/img-3.jpg',
    },
    {
        Id: '7',
        sImgS: 'images/service-single/sm/img-1.jpg',
        sTitle: 'Manual Testing',
        description: 'Ensuring software quality with meticulous manual testing for error-free performance.',
        des2: 'Specializing in identifying bugs and usability issues to enhance reliability.',
        des3: 'Providing detailed reports to help improve your software’s functionality and performance.',
        icon: 'flaticon-social-media',
        ssImg1: 'images/service-single/sm/img-2.jpg',
        ssImg2: 'images/service-single/sm/img-3.jpg',
    },
    {
        Id: '8',
        sImgS: 'images/service-single/dm/img-1.jpg',
        sTitle: 'Performance Testing',
        description: 'Optimizing software performance by identifying bottlenecks and improving speed.',
        des2: 'Expert in load testing, stress testing, and scalability assessments.',
        des3: 'Ensuring your application performs seamlessly under varying conditions.',
        icon: 'flaticon-promotion',
        ssImg1: 'images/service-single/dm/img-2.jpg',
        ssImg2: 'images/service-single/dm/img-3.jpg',
    },
    {
        Id: '9',
        sImgS: 'images/service-single/email/img-1.jpg',
        sTitle: 'Automation Testing',
        description: 'Streamlining the testing process with automation tools for faster delivery.',
        des2: 'Specializing in creating reusable test scripts to ensure consistent software quality.',
        des3: 'Saving time and resources by automating repetitive testing tasks efficiently.',
        icon: 'flaticon-email-marketing',
        ssImg1: 'images/service-single/email/img-2.jpg',
        ssImg2: 'images/service-single/email/img-3.jpg',
    },
];

export default Services;
